//
//  PresentationExchangeMocks.generated.swift
//  PresentationExchange
//
//  Generated by Mockingbird v0.20.0.
//  DO NOT EDIT
//

// swiftlint:disable all

@testable import Mockingbird
@testable import PresentationExchange
import Foundation
import JSONSchema
import Sextant
import Swift

// No mocks used in 'PresentationExchangeTests'. Mockingbird is configured to only generate mocks
// for types that are explicitly initialized in your tests with `mock(SomeType.self)`. For more
// information, see 'Thunk Pruning' in the README.
