# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Code coverage"
  lane :code_coverage do
    
    # You can convert the generated report to JSON using the following command:
    # xcrun xccov view xcov_output/xccovreport-0.xccovreport --json
    
    params = {
      package_path: '.',
      scheme: 'PresentationExchange',
      devices: ['iPhone 14'],
      output_directory: "xcov_output",
      result_bundle: true
    }

    if ENV['CI']
      params[:xcargs] = "-skipPackagePluginValidation"
    end

    run_tests(params)

    xcov(
      scheme: "PresentationExchange",
      output_directory: "xcov_output",
      is_swift_package: true,
      minimum_coverage_percentage: 70.0
    )
    if ENV['CI'] != 'true'
      sh 'open ../xcov_output/index.html'
    end
  end
  
  desc "Runs unit tests"
  lane :tests do
    
    sh("ls /Applications/")

    params = {
      package_path: '.',
      scheme: 'PresentationExchange',
      devices: [
        'iPhone 14'
      ], 
      result_bundle: true
    }

    if ENV['CI'] 
      params[:xcargs] = "-skipPackagePluginValidation"
    end

    run_tests(params)
  end

  desc "Builds the package"
  lane :just_build do
    xcodebuild(
      scheme: "PresentationExchange",
      destination: "platform=iOS Simulator,OS=16.2,name=iPhone 8",
      xcargs: "-skipPackagePluginValidation"
    )
  end
end
