# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Runs unit tests"
  lane :tests do
    params = {
      package_path: '.',
      scheme: 'PresentationExchange',
      devices: ['iPhone 14'], 
      result_bundle: true
    }

    if ENV['CI'] 
      params[:xcargs] = "-skipPackagePluginValidation"
    end

    run_tests(params)
  end

  desc "Builds the package"
  lane :just_build do
    xcodebuild(
      scheme: "PresentationExchange",
      destination: "platform=iOS Simulator,OS=16.2,name=iPhone 8",
      xcargs: "-skipPackagePluginValidation"
    )
  end
end
